name: PlatformIO CI

on:
  push:
    branches:
      - master
      
env:
  TASMOTA_VERSION: 13.2.0
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download Tasmota git
        run: git clone -b v${{ env.TASMOTA_VERSION }} https://github.com/arendst/Tasmota.git Tasmota-${{ env.TASMOTA_VERSION }}
        
      - name: List directory Files
        run: ls -lh

      - name: Copy NicolasBernaerts Files
        run: |
             mv ./teleinfo/platformio_override.ini ${{ env.TASMOTA_VERSION }}/platformio_override.ini
             mv ./teleinfo/platformio_override.ini ${{ env.TASMOTA_VERSION }}/platformio_override.ini
             mv ./teleinfo/user_config_override.h ${{ env.TASMOTA_VERSION }}/tasmota/user_config_override.h	
             mv ./common/partition/esp32_partition_4M_app1800k_fs1200k.csv ${{ env.TASMOTA_VERSION }}/partition/esp32_partition_4M_app1800k_fs1200k.csv
             mv ./common/partition/esp32_partition_8M_app3M_fs4M.csv ${{ env.TASMOTA_VERSION }}/partition/esp32_partition_8M_app3M_fs4M.csv
             mv ./common/partition/esp32_partition_16M_app3M_fs12M.csv ${{ env.TASMOTA_VERSION }}/partition/esp32_partition_16M_app3M_fs12M.csv
             mv ./common/board/esp8266_16M14M.json ${{ env.TASMOTA_VERSION }}/boards/esp8266_16M14M.json
             mv ./common/board/esp32_4M1200k.json ${{ env.TASMOTA_VERSION }}/boards/esp32_4M1200k.json
             mv ./common/board/esp32s2_4M1200k.json ${{ env.TASMOTA_VERSION }}/boards/esp32s2_4M1200k.json
             mv ./common/board/denkyd4_8M4M-safeboot.json ${{ env.TASMOTA_VERSION }}/boards/denkyd4_8M4M-safeboot.json
             mv ./common/board/esp32s3_16M12M-safeboot.json ${{ env.TASMOTA_VERSION }}/boards/esp32s3_16M12M-safeboot.json
             mv ./teleinfo/tasmota_type.h ${{ env.TASMOTA_VERSION }}/tasmota/include/tasmota_type.h
             mv ./teleinfo/xnrg_15_teleinfo.ino ${{ env.TASMOTA_VERSION }}/tasmota/tasmota_nrg_energy/xnrg_15_teleinfo.ino
             mv ./teleinfo/xdrv_01_9_webserver.ino ${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_01_9_webserver.ino
             mv ./common/xdrv_94_ip_address.ino ${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_94_ip_address.ino
             mv ./common/xdrv_96_ftp_server.ino ${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_96_ftp_server.ino
             mv ./common/xdrv_97_tcp_server.ino ${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_97_tcp_server.ino
             mv ./common/xdrv_98_esp32_board.ino ${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_98_esp32_board.ino
             mv ./teleinfo/xsns_104_teleinfo_graph.ino ${{ env.TASMOTA_VERSION }}/tasmota/tasmota_sns_sensor/xsns_104_teleinfo_graph.ino
             mv ./teleinfo/xsns_119_rte_server.ino ${{ env.TASMOTA_VERSION }}/tasmota/tasmota_sns_sensor/xsns_119_rte_server.ino
             unzip ./common/ArduinoJSON.zip -d ${{ env.TASMOTA_VERSION }}/lib/default/ArduinoJSON
             unzip ./common/FTPClientServer.zip -d ${{ env.TASMOTA_VERSION }}/lib/default/FTPClientServer


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio


      - name: Compile
        run: pio run
