name: PlatformIO CI

on:
  push:
    branches:
      - master
      
env:
  TASMOTA_VERSION: 13.2.0
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Download Tasmota git
        run: git clone -b v${{ env.TASMOTA_VERSION }} https://github.com/arendst/Tasmota.git Tasmota-${{ env.TASMOTA_VERSION }}
        
      - name: List directory Files
        run: |
          ls -lh .
          ls -lh ./teleinfo
          pwd
      - name: Copy teleinfo/ Files
        run: |
          cd teleinfo/
          mv platformio_override.ini ../Tasmota-${{ env.TASMOTA_VERSION }}/platformio_override.ini
          mv user_config_override.h ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/user_config_override.h
          mv tasmota_types.h ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/include/tasmota_types.h
          mv xnrg_15_teleinfo.ino ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/tasmota_nrg_energy/xnrg_15_teleinfo.ino
          mv xdrv_01_9_webserver.ino ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_01_9_webserver.ino
          mv xsns_104_teleinfo_graph.ino ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/tasmota_sns_sensor/xsns_104_teleinfo_graph.ino
          mv xsns_119_rte_server.ino ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/tasmota_sns_sensor/xsns_119_rte_server.ino

      - name: Copy common/ Files
        run: |
          cd common/
          mv ./partition/esp32_partition_4M_app1800k_fs1200k.csv ../Tasmota-${{ env.TASMOTA_VERSION }}/partition/esp32_partition_4M_app1800k_fs1200k.csv
          mv ./partition/esp32_partition_8M_app3M_fs4M.csv ../Tasmota-${{ env.TASMOTA_VERSION }}/partition/esp32_partition_8M_app3M_fs4M.csv
          mv ./partition/esp32_partition_16M_app3M_fs12M.csv ../Tasmota-${{ env.TASMOTA_VERSION }}/partition/esp32_partition_16M_app3M_fs12M.csv
          mv ./board/esp8266_16M14M.json ../Tasmota-${{ env.TASMOTA_VERSION }}/boards/esp8266_16M14M.json
          mv board/esp32_4M1200k.json ../Tasmota-${{ env.TASMOTA_VERSION }}/boards/esp32_4M1200k.json
          mv board/esp32s2_4M1200k.json ../Tasmota-${{ env.TASMOTA_VERSION }}/boards/esp32s2_4M1200k.json
          mv board/denkyd4_8M4M-safeboot.json ../Tasmota-${{ env.TASMOTA_VERSION }}/boards/denkyd4_8M4M-safeboot.json
          mv board/esp32s3_16M12M-safeboot.json ../Tasmota-${{ env.TASMOTA_VERSION }}/boards/esp32s3_16M12M-safeboot.json
          mv xdrv_94_ip_address.ino ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_94_ip_address.ino
          mv xdrv_96_ftp_server.ino ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_96_ftp_server.ino
          mv xdrv_97_tcp_server.ino ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_97_tcp_server.ino
          mv xdrv_98_esp32_board.ino ../Tasmota-${{ env.TASMOTA_VERSION }}/tasmota/tasmota_drv_driver/xdrv_98_esp32_board.ino
          unzip ./ArduinoJSON.zip -d ../Tasmota-${{ env.TASMOTA_VERSION }}/lib/default/ArduinoJSON
          unzip .FTPClientServer.zip -d ../Tasmota-${{ env.TASMOTA_VERSION }}/lib/default/FTPClientServer

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Compile
        run: pio run
